# -*- coding: utf-8 -*-
"""
Build data/field_observations.json — a side lookup keyed by permit file_number
that carries ON-THE-GROUND field-observation data the YK scrapers cannot produce.

Source: municipal tracking table "טרם החלו בנייה" (permits issued but construction
not started), snapshot dated 24.3.26. Stored in scripts/sources/.

Why a side file (not a merge into all_permits.json):
  all_permits.json is regenerated by the biweekly scrapers, which would wipe any
  fields we injected. A standalone lookup keyed by file_number survives re-scrapes
  and is consulted at popup time. It also covers permits we don't yet track, so it
  auto-enriches them the moment they enter all_permits.json.

Output: { source, source_date, built_at, count, by_file: { "<file_number>": {...} } }
"""
import json, sys, os, argparse
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_SRC = os.path.join(HERE, "sources", "terem_helu_bniya_2026-03-24.xlsx")
DEFAULT_OUT = os.path.normpath(os.path.join(HERE, "..", "data", "field_observations.json"))
SOURCE_LABEL = "טבלת מעקב עירונית — היתרים טרם החלו בנייה"
SOURCE_DATE = "2026-03-24"

# xlsx header -> output key. None values are read but not emitted directly.
COLS = {
    "תיק היתר": "file_number",
    "שכונה": "neighborhood",
    "רחוב": "street",
    "בית": "house",
    "סוג היתר בינוי": "permit_type",
    "תאריך ביקור אחרון באתר גם אם לא החלה בנייה": "visit_date",
    "סטאטוס בנייה לפי הביקור האחרון": "field_status",
    "תיאור": "description",
    "פרטי יזם": "developer",
    "סטטוס יזם": "developer_status",
    "סטטוס תיק רישוי מלא": "licensing_status",
    "צפי להתחלת ביצוע  לפי רבעון": "eta_quarter",
    "פרק זמן בין היתר שהופק לביצוע": "permit_to_exec_gap",
    "הערות 24.3.26": "notes",
}
DATE_KEYS = {"visit_date"}
# An entry is kept only if it carries at least one of these (i.e. real observation value).
OBS_KEYS = ("field_status", "visit_date", "eta_quarter", "developer",
            "developer_status", "licensing_status", "notes", "description")


def clean(v, is_date):
    if v is None:
        return None
    try:
        if pd.isna(v):  # catches float NaN and pandas NaT
            return None
    except (TypeError, ValueError):
        pass
    if isinstance(v, pd.Timestamp) or (is_date and hasattr(v, "strftime")):
        try:
            return pd.Timestamp(v).strftime("%Y-%m-%d")
        except Exception:
            pass
    s = str(v).strip()
    return s or None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=DEFAULT_SRC)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--built-at", default="", help="ISO timestamp (CI passes one; keeps build deterministic)")
    args = ap.parse_args()

    df = pd.read_excel(args.src, sheet_name=0, header=0)
    missing = [h for h in COLS if h not in df.columns]
    if missing:
        sys.exit("Missing expected columns: " + ", ".join(missing))

    by_file = {}
    skipped_no_file = skipped_no_obs = dup = 0
    for _, row in df.iterrows():
        rec = {}
        for header, key in COLS.items():
            val = clean(row.get(header), key in DATE_KEYS)
            if val is not None:
                rec[key] = val
        fn = rec.pop("file_number", None)
        if not fn:
            skipped_no_file += 1
            continue
        if not any(k in rec for k in OBS_KEYS):
            skipped_no_obs += 1
            continue
        rec["source"] = SOURCE_LABEL
        rec["source_date"] = SOURCE_DATE
        if fn in by_file:
            dup += 1
            # keep the row with the most recent visit_date
            old = by_file[fn].get("visit_date", "")
            new = rec.get("visit_date", "")
            if new <= old:
                continue
        by_file[fn] = rec

    out = {
        "source": SOURCE_LABEL,
        "source_date": SOURCE_DATE,
        "built_at": args.built_at,
        "count": len(by_file),
        "by_file": by_file,
    }
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)

    print(f"wrote {args.out}")
    print(f"  entries: {len(by_file)}  (skipped no-file:{skipped_no_file}, no-obs:{skipped_no_obs}, dup-collapsed:{dup})")
    fs = sum(1 for r in by_file.values() if "field_status" in r)
    eta = sum(1 for r in by_file.values() if "eta_quarter" in r)
    dev = sum(1 for r in by_file.values() if "developer" in r)
    print(f"  with field_status:{fs}  eta_quarter:{eta}  developer:{dev}")


if __name__ == "__main__":
    main()
