# -*- coding: utf-8 -*-
"""
Build / update data/occupancy_status.json — a side lookup keyed by PLAN id
(e.g. "101-0477240") that marks plans which reached טופס 4 / גמר בנייה and are
occupied (מאוכלס). The app consults it at style/popup/filter time to override the
displayed status to "מאוכלס" and (stage ב') to move the plan's units out of the
future pipeline into the existing state.

Why a side file (mirrors build_field_observations.py):
  plans.geojson / GS are regenerated by scrapers, which would wipe an injected
  status. A standalone lookup keyed by plan_name survives re-builds and is applied
  at render time. status_mavat stays the true PLANNING status (from Mavat); this
  file carries the orthogonal built/occupied fact.

Sources (layered, see plan indexed-beaming-cake.md):
  1. Authoritative — an xlsx export from אגף פיקוח על הבנייה filtered to permits
     that reached טופס 4 / גמר עבודה (sister to the "טרם החלו בנייה" table).
  2. Manual entries maintained directly in occupancy_status.json (e.g. סן מרטין
     23-25 seeded before the export exists).

This script PRESERVES manual entries already in occupancy_status.json and only
adds/updates from the xlsx — it never deletes hand-added plans.

Usage:
  py build_occupancy_status.py                 # re-count/normalize existing file only
  py build_occupancy_status.py --src <xlsx>    # merge a פיקוח export into the file
"""
import json, os, argparse, re

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.normpath(os.path.join(HERE, "..", "data", "occupancy_status.json"))
SOURCE_LABEL = "תצפית שטח / פיקוח על הבנייה"

# xlsx header -> output key. Kept permissive: only a plan-id column is required.
# Adjust these once the real פיקוח export schema is known.
COLS = {
    "מספר תכנית": "plan_name",
    "תכנית": "plan_name",
    "תאריך טופס 4": "form4_date",
    "תאריך אכלוס": "form4_date",
    "סטטוס": "occupancy_status",
    "הערות": "notes",
    "מקור": "source",
}
PLAN_ID_KEYS = ("מספר תכנית", "תכנית")


def normalize_plan_name(raw):
    """Return canonical 'NNN-DDDDDDD' plan id (matches plans.geojson plan_name)."""
    s = str(raw or "").strip()
    if not s:
        return ""
    # already canonical
    if re.match(r"^\d{3}-\d{6,7}$", s):
        return s
    digits = re.sub(r"\D", "", s)
    # Mavat plan numbers here are district 101 + 6/7-digit serial
    if digits.startswith("101") and len(digits) >= 9:
        return "101-" + digits[3:]
    if len(digits) >= 6:  # bare serial -> assume district 101
        return "101-" + digits
    return s


def clean(v):
    if v is None:
        return None
    try:
        import pandas as pd
        if pd.isna(v):
            return None
        if hasattr(v, "strftime"):
            return pd.Timestamp(v).strftime("%Y-%m-%d")
    except Exception:
        pass
    return (str(v).strip() or None)


def load_existing(path):
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return data.get("by_plan", {}) or {}
    return {}


def merge_xlsx(by_plan, src):
    import pandas as pd
    df = pd.read_excel(src, sheet_name=0, header=0)
    id_header = next((h for h in PLAN_ID_KEYS if h in df.columns), None)
    if not id_header:
        raise SystemExit("xlsx missing a plan-id column (one of: %s)" % ", ".join(PLAN_ID_KEYS))
    added = updated = 0
    for _, row in df.iterrows():
        key = normalize_plan_name(row.get(id_header))
        if not key:
            continue
        rec = {}
        for header, okey in COLS.items():
            if header in df.columns:
                val = clean(row.get(header))
                if val is not None and okey != "plan_name":
                    rec[okey] = val
        rec.setdefault("occupancy_status", "מאוכלס")
        rec.setdefault("source", SOURCE_LABEL)
        if key in by_plan:
            by_plan[key].update({k: v for k, v in rec.items() if v})
            updated += 1
        else:
            by_plan[key] = rec
            added += 1
    return added, updated


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="", help="optional פיקוח xlsx export to merge")
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--built-at", default="", help="ISO timestamp (CI passes one)")
    args = ap.parse_args()

    by_plan = load_existing(args.out)
    before = len(by_plan)
    added = updated = 0
    if args.src:
        added, updated = merge_xlsx(by_plan, args.src)

    # normalize keys (in case manual entries used a non-canonical plan id)
    normed = {}
    for k, v in by_plan.items():
        normed[normalize_plan_name(k)] = v
    by_plan = normed

    out = {
        "source": SOURCE_LABEL,
        "source_date": "",
        "built_at": args.built_at,
        "count": len(by_plan),
        "by_plan": by_plan,
    }
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)

    print(f"wrote {args.out}")
    print(f"  plans: {len(by_plan)} (was {before}); merged from xlsx: +{added} new, {updated} updated")


if __name__ == "__main__":
    main()
